### PR TITLE
Fix: various issues

### PR DESCRIPTION
**Pull request by s520**
This PR contains many changes and improvements.

### Import
- Fixed a problem that files that are not UTF-8 or files with tabs cannot be read.
- Fixed a problem that texture files could not be read correctly.
- Preserve csv object's unique attributes in custom properties.

### Export
- Fixed an issue where Global scale was not working.
- Output csv object specific attributes from custom properties.

Please release as v0.6.0 after merging.

### CODE REVIEW

**Comment by maisvendoo** [comment]
Very good and greate job! Thank you very much for it! I released of version 0.6.0 with your changes

**Comment by s520** [comment]
Thank you for merging.
I confirmed that the chardet folder of "blenderCSV-v0.6.0.zip" is empty.
If this happens, an error will occur.
Please replace it with the attached zip file.
[blenderCSV-v0.6.0.zip](https://github.com/maisvendoo/blenderCSV/files/3800204/blenderCSV-v0.6.0.zip)

**Comment by maisvendoo** [comment]
Ok, file is changed

**Comment by s520** [comment]
Thanks!

**Pull request merged**
